package com.ffst.dustbinbrain.kotlin_mvp.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ffst.dustbinbrain.kotlin_mvp.bean.DustbinConfig;
import com.ffst.dustbinbrain.kotlin_mvp.bean.DustbinStateBean;
import com.ffst.dustbinbrain.kotlin_mvp.bean.UserMessage;

import com.ffst.dustbinbrain.kotlin_mvp.bean.DustbinConfigDao;
import com.ffst.dustbinbrain.kotlin_mvp.bean.DustbinStateBeanDao;
import com.ffst.dustbinbrain.kotlin_mvp.bean.UserMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dustbinConfigDaoConfig;
    private final DaoConfig dustbinStateBeanDaoConfig;
    private final DaoConfig userMessageDaoConfig;

    private final DustbinConfigDao dustbinConfigDao;
    private final DustbinStateBeanDao dustbinStateBeanDao;
    private final UserMessageDao userMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dustbinConfigDaoConfig = daoConfigMap.get(DustbinConfigDao.class).clone();
        dustbinConfigDaoConfig.initIdentityScope(type);

        dustbinStateBeanDaoConfig = daoConfigMap.get(DustbinStateBeanDao.class).clone();
        dustbinStateBeanDaoConfig.initIdentityScope(type);

        userMessageDaoConfig = daoConfigMap.get(UserMessageDao.class).clone();
        userMessageDaoConfig.initIdentityScope(type);

        dustbinConfigDao = new DustbinConfigDao(dustbinConfigDaoConfig, this);
        dustbinStateBeanDao = new DustbinStateBeanDao(dustbinStateBeanDaoConfig, this);
        userMessageDao = new UserMessageDao(userMessageDaoConfig, this);

        registerDao(DustbinConfig.class, dustbinConfigDao);
        registerDao(DustbinStateBean.class, dustbinStateBeanDao);
        registerDao(UserMessage.class, userMessageDao);
    }
    
    public void clear() {
        dustbinConfigDaoConfig.clearIdentityScope();
        dustbinStateBeanDaoConfig.clearIdentityScope();
        userMessageDaoConfig.clearIdentityScope();
    }

    public DustbinConfigDao getDustbinConfigDao() {
        return dustbinConfigDao;
    }

    public DustbinStateBeanDao getDustbinStateBeanDao() {
        return dustbinStateBeanDao;
    }

    public UserMessageDao getUserMessageDao() {
        return userMessageDao;
    }

}
